### ISSUE TITLE
Connection dies after a few seconds

### ISSUE THREAD

**Issue by DariusPrime** [arduino/wifishield#9]
Hi,
I am using WiFi Shield R3 connected to the Arduino Uno R3 like Server using this library. The Connection dies after a few seconds. Now to solve this issue, i send an "heartbeat" packet every "fixed_time" from Arduino in order to avoid the disconnection but i hope a fix is coming soon.

**Comment by mchrisb03** [comment]
The lwip (Light Weight IP)  tcp_poll function is being used by the firmware to define callback functions atcp_poll and atcp_poll_conn.

These are both checked roughly once every two seconds.

There is a value called tcp_poll_retries that is checked in these functions.  

The TCP connection is aborted when tcp_poll_retries is > 4 (so 5) in atcp_poll or when tcp_poll_retries is > 8 (so 9) in atcp_poll_conn.

The tcp_poll_retries value is incremented by 1 every two seconds no data is sent.

The tcp_poll_retries value only appears to get reset to 0 when data is successfully sent [tcp_data_sent].  

So, this appears to be an intentional mechanism used to kill the TCP connection when no data has been sent for 10 seconds or 18 seconds respectively.

The firmware and WiFi shield library should be modified to allow the user to configure or disable this timer.

I have tried to import the wifiHD project into Eclipse so I could look at making the change on the firmware side.

I have the AVR-Eclipse plugin installed.

However, like others have mentioned I am not able to successfully import this project into Eclipse.

Arduino Developers please update the github files (or provide additional instructions) so that the user base can start to make changes.
